mail:
  conf:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    recipient: ${MAIL_RECIPIENT}

spring:
  redis:
    url: ${REDIS_URL}

  config:
    activate:
      on-profile: ${SPRING_PROFILES}