spring:
  profiles:
    active: ${SPRING_PROFILE:prod}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: off
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:piter}?serverTimezone=UTC
    username: piter
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      validation-timeout: 360000
  flyway:
    enabled: true
  cloud:
    openfeign:
      client:
        config:
          shorten-client:
            url: "https://shorten-link-fast-free-cool.ru"
  devtools:
    add-properties: false
telegram:
  bot:
    name: piter_discount_bot
    token: ${TELEGRAM_TOKEN}

logging:
  config: classpath:logback-local.xml