mail:
  conf:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    recipient: ${MAIL_RECIPIENT}

spring:
  redis:
    url: ${REDIS_URL}

  profiles:
    active: ${SPRING_PROFILES}